<?php
class AODto extends ArrayObject
{
    public function __construct()
    {
        //$this->setFlags(ArrayObject::STD_PROP_LIST|ArrayObject::ARRAY_AS_PROPS);
        //$this->setFlags(ArrayObject::ARRAY_AS_PROPS);


    }

    public function __call($func, $argv)
    {
        throw new Exception(__FUNCTION__);
    }

    /**
     * Getter
     *
     */
    public function offsetGet($index)
    {
        //throw new Exception(__FUNCTION__);
        parent::offsetGet($index); // TODO: Change the autogenerated stub
    }

    public function offsetSet($index, $newval)
    {
        //throw new Exception(__FUNCTION__);
        parent::offsetSet($index, $newval); // TODO: Change the autogenerated stub
    }

    public function append($value)
    {
        //throw new Exception(__FUNCTION__);
        parent::append($value); // TODO: Change the autogenerated stub
    }

    public function offsetExists($val)
    {
        throw new Exception(__FUNCTION__);
    }
}


$dto = new AODto();
$dto[] = 'funk'; // offsetSet
//$dto->hobbies[] = 'billiards';

//$dto->firstname = 'Bob';
//print $dto->firstname;
//$dto->hobbies[] = 'billiards';
//print_r($dto->hobbies);
//$dto->mother->firstname = 'Karen';
//$dto['firstname'] = 'George';

//print $dto['mother']['firstname']; // <--- This won't work
//print_r($dto);


